POST https://prlu3fxzgi.execute-api.us-east-1.amazonaws.com/dev/subscribe
Content-Type: application/json

{
  "email": "nabove6368@edxplus.com",
  "privacyPolicyAcceptedAt": "2022-01-01T00:00:00.000Z"
}
###
POST https://prlu3fxzgi.execute-api.us-east-1.amazonaws.com/dev/subscribe
Content-Type: application/json

{
  "email": "typescriptteatime@gmail.com",
  "privacyPolicyAcceptedAt": "2022-01-01T00:00:00.000Z"
}

###
POST https://prlu3fxzgi.execute-api.us-east-1.amazonaws.com/dev/subscribe
Content-Type: application/json

{
  "email": "gidey59108@dineroa.com",
  "privacyPolicyAcceptedAt": "2022-01-01T00:00:00.000Z"
}
###
POST https://prlu3fxzgi.execute-api.us-east-1.amazonaws.com/dev/subscribe
Content-Type: application/json

{
  "email": "hi",
  "privacyPolicyAcceptedAt": "2022-01-01T00:00:00.000Z"
}

###
POST https://prlu3fxzgi.execute-api.us-east-1.amazonaws.com/dev/subscribe
Content-Type: application/json

{
  "email": "typescriptteatime@gmail.com",
  "privacyPolicyAcceptedAt": "2022-01-01T00:00:00.000Z"
}

### instead use
GET https://prlu3fxzgi.execute-api.us-east-1.amazonaws.com/dev/unsubscribe?id=89de335f-00e0-43e1-8784-27f0f5afa625
