POST https://prlu3fxzgi.execute-api.us-east-1.amazonaws.com/subscribe
Content-Type: application/json

{
  "email": "nabove6368@edxplus.com",
  "privacyPolicyAcceptedAt": "2022-01-01T00:00:00.000Z"
}
###
POST https://prlu3fxzgi.execute-api.us-east-1.amazonaws.com/subscribe
Content-Type: application/json

{
  "email": "typescriptteatime@gmail.com",
  "privacyPolicyAcceptedAt": "2022-01-01T00:00:00.000Z"
}

###
POST https://prlu3fxzgi.execute-api.us-east-1.amazonaws.com/subscribe
Content-Type: application/json

{
  "email": "gidey59108@dineroa.com",
  "privacyPolicyAcceptedAt": "2022-01-01T00:00:00.000Z"
}
###
POST https://prlu3fxzgi.execute-api.us-east-1.amazonaws.com/dev/subscribe
Content-Type: application/json

{
  "email": "hi",
  "privacyPolicyAcceptedAt": "2022-01-01T00:00:00.000Z"
}
###
POST https://prlu3fxzgi.execute-api.us-east-1.amazonaws.com/dev/subscribe
Content-Type: application/json

{
  "email": "typescriptteatime@gmail.com",
  "privacyPolicyAcceptedAt": "2022-01-01T00:00:00.000Z"
}

###
GET https://prlu3fxzgi.execute-api.us-east-1.amazonaws.com/dev/unsubscribe2?email=typescriptteatime@gmail.com

