version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 3142:5432
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 3143:8080
