version: "3"

services:
  db:
    image: bagelbits/5e-database:latest

  cache:
    image: redis:6.2.3

  api:
    environment:
      MONGODB_URI: mongodb://db/5e-database
      REDIS_URL: redis://cache
    image: bagelbits/5e-srd-api:latest
    ports:
      - "3001:3000"
    depends_on:
      - db
      - cache
