openapi: "3.0.1"
info:
  title: "Newsletter"
  description: "API for managing blog email newsletter"
  version: "2022-09-16 10:21:56UTC"
servers:
- url: "https://evef8ow37e.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
paths:
  # /unsubscribe:
  #   get:
  #     responses:
  #       default:
  #         description: "Default response for GET /unsubscribe"
  #     x-amazon-apigateway-integration:
  #       integrationSubtype: "StepFunctions-StartExecution"
  #       credentials: "arn:aws:iam::756399734264:role/ApiGatewayExecutionRoleForStepFunctionsNewsletterUnsubscribe"
  #       requestParameters:
  #         Input: "$request.querystring.input"
  #         StateMachineArn: "arn:aws:states:us-east-1:756399734264:stateMachine:NewsletterUnsubscribe"
  #       payloadFormatVersion: "1.0"
  #       type: "aws_proxy"
  #       connectionType: "INTERNET"
  #       timeoutInMillis: 30000
  /subscribe:
    post:
      responses:
        default:
          description: "Default response for POST /subscribe"
      x-amazon-apigateway-integration:
        integrationSubtype: "StepFunctions-StartExecution"
        credentials: 
          Fn::GetAtt: [HttpApiSubscribeRole, Arn]
        requestParameters:
          Input: "$request.body"
          StateMachineArn: 
            Fn::GetAtt: [SubscribeSfn, Arn]
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        connectionType: "INTERNET"
x-amazon-apigateway-cors:
  allowMethods:
  - "POST"
  allowHeaders:
  - "content-type"
  maxAge: -42
  allowCredentials: false
  allowOrigins:
  - "https://www.example.com"
x-amazon-apigateway-importexport-version: "1.0"