version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "should-send-newsletter"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jub5ykce0thl"
s3_prefix = "should-send-newsletter"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
