AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  should-send-newsletter

  Sample SAM Template for should-send-newsletter

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # how long can the lambda functions run until they abort with an error
    Timeout: 3

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        "Fn::Transform":
          Name: "AWS::Include"
          Parameters:
            Location: api.yaml

  HttpApiSubscribeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: StepFunctionsStartExecutionOfNewsletterSubscribe
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !GetAtt SubscribeSfn.Arn

  HttpApiUnsubscribeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: StepFunctionsStartExecutionOfNewsletterUnsubscribe
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !GetAtt UnsubscribeSfn.Arn

  SubscribeSfn:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: Subscribe
      DefinitionUri: state-machines/subscribe.asl.json
      DefinitionSubstitutions:
        ContactListName: !Ref NewsletterContactList
        EmailSource: !Ref SesIdentity
        WelcomeEmailTemplate: !Ref WelcomeEmailTemplate
      Policies:
        - Statement:
            - Sid: SESSendWelcomeEmail
              Effect: Allow
              Action:
                - ses:SendTemplatedEmail
              Resource:
                - !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/*"
                - !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:template/${WelcomeEmailTemplate}"
            - Sid: SESCreateContact
              Effect: Allow
              Action:
                - ses:CreateContact
              Resource: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:contact-list/${NewsletterContactList}"

  UnsubscribeSfn:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: Unsubscribe
      DefinitionUri: state-machines/unsubscribe.asl.json
      DefinitionSubstitutions:
        ContactListName: !Ref NewsletterContactList
      Policies:
        - Statement:
            - Sid: SESDeleteContact
              Effect: Allow
              Action:
                - ses:DeleteContact
              Resource: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:contact-list/${NewsletterContactList}"

  NewsletterSfn:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: NewsletterDaily
      DefinitionUri: newsletter.asl.json
      DefinitionSubstitutions:
        HasNewBlogArticleFunctionArn: !GetAtt HasNewBlogArticleFunction.Arn
        ChunkContactsFunctionArn: !GetAtt ChunkContactsFunction.Arn
        TransformToSendBulkEmailFunctionArn: !GetAtt TransformToSendBulkEmailFunction.Arn
        ContactListName: !Ref NewsletterContactList
      Events:
        Schedule:
          Type: Schedule # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#schedule
          Properties:
            Schedule: cron(0 4 * * ? *)
            Description: Invoke every day at 4am UTC
            Enabled: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref HasNewBlogArticleFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ChunkContactsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref TransformToSendBulkEmailFunction
        - Statement:
            - Sid: SESListContactsPolicy
              Effect: Allow
              Action:
                - ses:ListContacts
              Resource: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:contact-list/${NewsletterContactList}"
            - Sid: SESSendBulkEmailPolicy
              Effect: Allow
              Action:
                - ses:SendBulkEmail
              Resource:
                - !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/*"
                - !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:template/${NewBlogArticleEmailTemplate}"
            - Sid: SESSendBulkTemplatedEmailPolicy
              Effect: Allow
              Action:
                - ses:SendBulkTemplatedEmail
              Resource:
                - !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/*"
                - !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:template/${NewBlogArticleEmailTemplate}"

  HasNewBlogArticleFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: has-new-blog-article/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          RSS_FEED_URL: "https://dev.to/rss"
      Runtime: nodejs16.x
      Architectures:
        - x86_64
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - app.ts

  ChunkContactsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: chunk-contacts/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          CHUNK_SIZE: "50"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints:
          - app.ts

  TransformToSendBulkEmailFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: transform-to-send-bulk-email/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          TEMPLATE_ARN: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:template/${NewBlogArticleEmailTemplate}"
          FROM_EMAIL_ADDRESS: !Ref SesIdentity
          TEMPLATE_NAME: !Ref NewBlogArticleEmailTemplate
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints:
          - app.ts

  NewBlogArticleEmailTemplate:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: NewBlogArticle
        SubjectPart: "New Article: {{articleTitle}}"
        HtmlPart: !Sub '<h1>New article:{{articleTitle}}</h1><p>Hi{{email}},</p><p>Thank you always for reading our blog.</p><p>We just finished another article that you might be interested in.</p><div style="padding: 16px;background:#1FD760;width:fit-content;border-radius: 30px;"> <a href="{{linkToArticle}}" style="color:#151E18;font-family:Helvetica, sans-serif;font-size:18px;font-weight:600;line-height:120%;Margin:0;text-decoration:none;text-transform:uppercase;" target="_blank"> Read the article now </a></div><p>Click here to <a href="https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/unsubscribe?input=%7B%22email%22:%22{{email}}%22%7D"  target="_blank">unsubscribe</a>.</p>'
        TextPart: !Sub 'Hi {{email}}, Thank you always for reading our blog. We just finished another article "{{articleTitle}}" that you might be interested in. To read the article, copy the following link into your browsers address bar: {{linkToArticle}}. To unsubscribe, use the following link https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/unsubscribe?input=%7B%22email%22:%22{{email}}%22%7D'

  WelcomeEmailTemplate:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: Welcome
        SubjectPart: Welcome to the Newsletter
        HtmlPart: "<h1>Welcome to the Newsletter</h1><p>Hi {{email}},</><p>You will receive a new email whenever there is a new blog post.</p>"
        TextPart: "Welcome to the Newsletter. You will receive a new email whenever there is a new blog post."

  NewsletterContactList:
    Type: AWS::SES::ContactList
    DeletionPolicy: Delete
    Properties:
      ContactListName: EmailNewsletter
      Description: Creating a contact list example
      Topics:
        - TopicName: Newsletter
          DisplayName: Blog Post Newsletter
          Description: Never miss a new blog post by subscribing to our newsletter.
          DefaultSubscriptionStatus: OPT_OUT

  SesIdentity:
    Type: AWS::SES::EmailIdentity
    DeletionPolicy: Delete
    Properties:
      EmailIdentity: "typescriptteatime@gmail.com"

Outputs:
  EmailIdentity:
    Description: The email address used to send emails from
    Value: !Ref SesIdentity
  TryingToGenArn:
    Description: "TryingToGen Email Template ARN"
    Value: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:template/${WelcomeEmailTemplate}"
  ApiBasePath:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  HasNewBlogArticleFunction:
    Description: "HasNewBlogArticle Lambda Function ARN"
    Value: !GetAtt HasNewBlogArticleFunction.Arn
  HasNewBlogArticleFunctionIamRole:
    Description: "Implicit IAM Role created for HasNewBlogArticle function"
    Value: !GetAtt HasNewBlogArticleFunctionRole.Arn
  NewsletterSfnArn:
    Description: "Blog Newsletter state machine ARN"
    Value: !Ref NewsletterSfn
  NewsletterSfnRole:
    Description: "IAM Role created for Blog Newsletter state machine based on the specified SAM Policy Templates"
    Value: !GetAtt NewsletterSfnRole.Arn
