GET http://localhost:3000/adventurers

###

GET http://localhost:3000/adventurers/Pickle Rick

### 

GET http://localhost:3000/adventurers/notfound

###
POST http://localhost:3000/adventurers
Content-Type: application/json

{
    "username": "Pickle Rick",
    "level": 9001,
    "experience": 9132831,
    "nonexistent": true
}


### erroneous username

POST http://localhost:3000/adventurers
Content-Type: application/json

{
    "username": 1,
    "experience": 9132831,
    "nonexistent": true
}

###

PATCH http://localhost:3000/adventurers
Content-Type: application/json

{
    "username": "Pickle Rick",
    "experience": 100
}

###
DELETE http://localhost:3000/adventurers

###

GET http://localhost:3000/