GET http://localhost:3000/adventurers

###

GET http://localhost:3000/adventurers/Pickle Rick

### 

GET http://localhost:3000/adventurers/notfound

###
POST http://localhost:3000/adventurers
Content-Type: application/json

{
    "username": "Pickle Rick",
    "level": 9001,
    "experience": 9132831,
    "nonexistent": true
}


### erroneous username

POST http://localhost:3000/adventurers
Content-Type: application/json

{
    "username": 1,
    "experience": 9132831,
    "nonexistent": true
}

###

PATCH http://localhost:3000/adventurers
Content-Type: application/json

{
    "username": "maceisgrace",
    "hp": 75
}

###
DELETE http://localhost:3000/adventurers

###

GET http://localhost:3000/


### GET battles

GET http://localhost:3000/battles

### Test create battle
GET http://localhost:3000/battles/test
### 
GET http://localhost:3000/battles/test2

### Emit Leveled Up test events
POST http://localhost:3000/test-websockets
Content-Type: application/json

{
  "level": 12,
  "target": "Amazing Adventurer 1",
  "type": "leveled up"
}

### 
POST http://localhost:3000/test-websockets
Content-Type: application/json

{
  "type": "fire cast",
  "actor": "Amazing Adventurer 1",
  "target": "chain devil"
}