AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  toilet-paper-tracker

  Sample SAM Template for toilet-paper-tracker

Resources:
  Table:
    Type: AWS::Serverless::SimpleTable # More info about SimpleTable Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: toilet-paper-tracker

  ApiGwUser:
    Type: AWS::IAM::User
    Properties:
      UserName: toilet-paper-tracker-api-gw-user
      Policies:
        - PolicyName: toilet-paper-tracker-rw-dynamodb
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                  - dynamodb:PutItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:BatchGetItem
                  - dynamodb:DescribeTable
                  - dynamodb:ConditionCheckItem
                Resource:
                  - Fn::Sub:
                      - arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}
                      - tableName:
                          Ref: Table
                  - Fn::Sub:
                      - arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}/index/*
                      - tableName:
                          Ref: Table

  ApiGwUserAccessKey3:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref ApiGwUser
      Status: Active

Outputs:
  PutTable:
    Description: "DynamoDB table name"
    Value: !GetAtt Table.Arn
  ApiGwUserAccessKeyId:
    Value: !Ref ApiGwUserAccessKey3
  # ApiGwUserSecretAccessKey:
  #   Value: !GetAtt ApiGwUserAccessKey3.SecretAccessKey
