import { Button, Text, VStack } from "@chakra-ui/react";
import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import AddPlantedTrees from "../components/AddPlantedTrees";
import Forest from "../components/Forest";
import IndexHeader from "../components/IndexHeader";
import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack
        as="main"
        padding={{ md: 20, base: 4 }}
        // override padding top must come after padding
        pt={20}
        gap={8}
      >
        <IndexHeader />
        <AddPlantedTrees />
        <Forest />
      </VStack>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <VStack>
      <Text>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </Text>
      <Button
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </Button>
    </VStack>
  );
};
