import { Button, Heading, Text, VStack } from "@chakra-ui/react";
// import { faTree } from "@fortawesome/free-solid-svg-icons";
// import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import AddPlantedTrees from "../components/AddPlantedTrees";
import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  // const Icon = chakra(FontAwesomeIcon);
  // <Icon icon={faTree} boxSize={6} color="brand.300" /

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack
        as="main"
        padding={{ md: 20, base: 4 }}
        // override padding top must come after padding
        pt={20}
        gap={8}
      >
        <VStack as="header" gap={8}>
          <Heading as="h1" size="4xl" textAlign={"center"}>
            Thousand Trees
          </Heading>
          <Heading
            as="h2"
            size={"lg"}
            textTransform="capitalize"
            textAlign={"center"}
          >
            Revert your Life Time Carbon Footprint to rescue our Planet
          </Heading>
        </VStack>

        {/* plant new trees  */}
        <AddPlantedTrees />

        {/* render planted trees  */}
        <VStack></VStack>
      </VStack>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <VStack>
      <Text>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </Text>
      <Button
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </Button>
    </VStack>
  );
};
