// ALL CREDIT GOES TO https://github.com/jforstneric/5e_encounter_generator
// AND THE MAKERS OF DnD. You rock!

const monsterData = [
  {
    name: 'doppelganger',
    area: 'city',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'gargoyle',
    area: 'city',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'wererat',
    area: 'city',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'rakshasa',
    area: 'city',
    type: 'fiend',
    hp: 1,
    maxDamage: 20,
  },
  {
    name: 'revenant',
    area: 'city',
    type: 'undead',
    hp: 1,
    maxDamage: 25,
  },
  {
    name: 'vampire',
    area: 'city',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'vampire spawn',
    area: 'city',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'blink dog',
    area: 'city',
    type: 'fey',
    hp: 1,
  },
  {
    name: 'acolyte',
    area: 'city',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'assassin',
    area: 'city',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'commoner',
    area: 'city',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'cultist',
    area: 'city',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'guard',
    area: 'city',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'thug',
    area: 'city',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'animated armor',
    area: 'dungeon',
    type: 'construct',
    hp: 1,
  },
  {
    name: 'flying sword',
    area: 'dungeon',
    type: 'construct',
    hp: 1,
  },
  {
    name: 'rug of smothering',
    area: 'dungeon',
    type: 'construct',
    hp: 1,
  },
  {
    name: 'banshee',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'beholder',
    area: 'dungeon',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'death tyrant',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'spectator',
    area: 'dungeon',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'crawling claw',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'death knight',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'demilich',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'flameskull',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'ghost',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'ghast',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'ghoul',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'gibbering mouther',
    area: 'dungeon',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'clay golem',
    area: 'dungeon',
    type: 'construct',
    hp: 1,
  },
  {
    name: 'flesh golem',
    area: 'dungeon',
    type: 'construct',
    hp: 1,
  },
  {
    name: 'iron golem',
    area: 'dungeon',
    type: 'construct',
    hp: 1,
  },
  {
    name: 'stone golem',
    area: 'dungeon',
    type: 'construct',
    hp: 1,
  },
  {
    name: 'gorgon',
    area: 'dungeon',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'grell',
    area: 'dungeon',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'helmed horror',
    area: 'dungeon',
    type: 'construct',
    hp: 1,
  },
  {
    name: 'homunculus',
    area: 'dungeon',
    type: 'construct',
    hp: 1,
  },
  {
    name: 'intellect devourer',
    area: 'dungeon',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'invisible stalker',
    area: 'dungeon',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'lamia',
    area: 'dungeon',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'lich',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'medusa',
    area: 'dungeon',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'dust mephit',
    area: 'dungeon',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'ice mephit',
    area: 'dungeon',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'magma mephit',
    area: 'dungeon',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'mud mephit',
    area: 'dungeon',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'smoke mephit',
    area: 'dungeon',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'steam mephit',
    area: 'dungeon',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'mimic',
    area: 'dungeon',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'mind flayer',
    area: 'dungeon',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'minotaur',
    area: 'dungeon',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'monodrone',
    area: 'dungeon',
    type: 'construct',
    hp: 1,
  },
  {
    name: 'duodrone',
    area: 'dungeon',
    type: 'construct',
    hp: 1,
  },
  {
    name: 'tridrone',
    area: 'dungeon',
    type: 'construct',
    hp: 1,
  },
  {
    name: 'quadrone',
    area: 'dungeon',
    type: 'construct',
    hp: 1,
  },
  {
    name: 'pentadrone',
    area: 'dungeon',
    type: 'construct',
    hp: 1,
  },
  {
    name: 'mummy',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'mummy lord',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'bone naga',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'spirit naga',
    area: 'dungeon',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'guardian naga',
    area: 'dungeon',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'black pudding',
    area: 'dungeon',
    type: 'ooze',
    hp: 1,
  },
  {
    name: 'gelatinous cube',
    area: 'dungeon',
    type: 'ooze',
    hp: 1,
  },
  {
    name: 'gray ooze',
    area: 'dungeon',
    type: 'ooze',
    hp: 1,
  },
  {
    name: 'ochre jelly',
    area: 'dungeon',
    type: 'ooze',
    hp: 1,
  },
  {
    name: 'shadow',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'shield guardian',
    area: 'dungeon',
    type: 'construct',
    hp: 1,
  },
  {
    name: 'skeleton',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'minotaur skeleton',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'warhorse skeleton',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'specter',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'wight',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'wraith',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'zombie',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'beholder zombie',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'ogre zombie',
    area: 'dungeon',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'aarakocra',
    area: 'other plane',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'azer',
    area: 'other plane',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'cambion',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'couatl',
    area: 'other plane',
    type: 'celestial',
    hp: 1,
  },
  {
    name: 'balor',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'barlgura',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'chasme',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'dretch',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'glabrezu',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'goristo',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'hezrou',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'manes',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'marilith',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'nalfeshnee',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'quasit',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'shadow demon',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'vrock',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'yochlol',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'barbed devil',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'bearded devil',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'bone devil',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'chain devil',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'erinyes',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'horned devil',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'ice devil',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'imp',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'lemure',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'pit fiend',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'spined devil',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'air elemental',
    area: 'other plane',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'earth elemental',
    area: 'other plane',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'fire elemental',
    area: 'other plane',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'water elemental',
    area: 'other plane',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'dao',
    area: 'other plane',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'djinni',
    area: 'other plane',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'efreeti',
    area: 'other plane',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'marid',
    area: 'other plane',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'hell hound',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'needle blight',
    area: 'forest',
    type: 'plant',
    hp: 1,
  },
  {
    name: 'twig blight',
    area: 'forest',
    type: 'plant',
    hp: 1,
  },
  {
    name: 'vine blight',
    area: 'forest',
    type: 'plant',
    hp: 1,
  },
  {
    name: 'driad',
    area: 'forest',
    type: 'fey',
    hp: 1,
  },
  {
    name: 'pixie',
    area: 'forest',
    type: 'fey',
    hp: 1,
  },
  {
    name: 'bugbear',
    area: 'nature',
    type: 'goblinoid',
    hp: 1,
  },
  {
    name: 'bugbear chief',
    area: 'nature',
    type: 'goblinoid',
    hp: 1,
  },
  {
    name: 'bulette',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'bullywug',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'centaur',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'chimera',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'cockatrice',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'cyclops',
    area: 'nature',
    type: 'giant',
    hp: 1,
  },
  {
    name: 'displacer beast',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'dracolich',
    area: 'nature',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'ettin',
    area: 'nature',
    type: 'giant',
    hp: 1,
  },
  {
    name: 'yellow faerie dragon',
    area: 'nature',
    type: 'fey',
    hp: 1,
  },
  {
    name: 'violet faerie dragon',
    area: 'nature',
    type: 'fey',
    hp: 1,
  },
  {
    name: 'galeb duhr',
    area: 'nature',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'cloud giant',
    area: 'nature',
    type: 'giant',
    hp: 1,
  },
  {
    name: 'fire giant',
    area: 'nature',
    type: 'giant',
    hp: 1,
  },
  {
    name: 'frost giant',
    area: 'nature',
    type: 'giant',
    hp: 1,
  },
  {
    name: 'hill giant',
    area: 'nature',
    type: 'giant',
    hp: 1,
  },
  {
    name: 'stone giant',
    area: 'nature',
    type: 'giant',
    hp: 1,
  },
  {
    name: 'storm giant',
    area: 'nature',
    type: 'giant',
    hp: 1,
  },
  {
    name: 'gnoll',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'gnoll pack lord',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'gnoll fang of yeenoghu',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'goblin',
    area: 'nature',
    type: 'goblinoid',
    hp: 1,
  },
  {
    name: 'goblin boss',
    area: 'nature',
    type: 'goblinoid',
    hp: 1,
  },
  {
    name: 'griffon',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'night hag',
    area: 'nature',
    type: 'fey',
    hp: 1,
  },
  {
    name: 'half-dragon',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'harpy',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'hippogriff',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'hobgoblin',
    area: 'nature',
    type: 'goblinoid',
    hp: 1,
  },
  {
    name: 'hobgoblin captain',
    area: 'nature',
    type: 'goblinoid',
    hp: 1,
  },
  {
    name: 'hobgoblin warlord',
    area: 'nature',
    type: 'goblinoid',
    hp: 1,
  },
  {
    name: 'hydra',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'jackalwere',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'kenku',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'winged kobold',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'kobold',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'kraken',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'lizardfolk',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'lizardfolk shaman',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'lizardfolk royal',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'werebear',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'wereboar',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'weretiger',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'werewolf',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'manticore',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'merfolk',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'merrow',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'nightmare',
    area: 'nature',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'ogre',
    area: 'nature',
    type: 'giant',
    hp: 1,
  },
  {
    name: 'half-ogre',
    area: 'nature',
    type: 'giant',
    hp: 1,
  },
  {
    name: 'oni',
    area: 'nature',
    type: 'giant',
    hp: 1,
  },
  {
    name: 'orc',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'orc war chief',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'orc eye of gruumsh',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'orog',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'owlbear',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'pegasus',
    area: 'nature',
    type: 'celestial',
    hp: 1,
  },
  {
    name: 'peryton',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'pseudodragon',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'purple worm',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'remorhaz',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'young remorhaz',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'roc',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'sahuagin',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'sahuagin priestess',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'sahuagin baron',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'satyr',
    area: 'nature',
    type: 'fey',
    hp: 1,
  },
  {
    name: 'scarecrow',
    area: 'nature',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'shambling mound',
    area: 'nature',
    type: 'plant',
    hp: 1,
  },
  {
    name: 'androsphinx',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'gynosphinx',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'sprite',
    area: 'nature',
    type: 'fey',
    hp: 1,
  },
  {
    name: 'stirge',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'tarrasque',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'thri-kreen',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'treant',
    area: 'nature',
    type: 'plant',
    hp: 1,
  },
  {
    name: 'troll',
    area: 'nature',
    type: 'giant',
    hp: 1,
  },
  {
    name: 'unicorn',
    area: 'nature',
    type: 'celestial',
    hp: 1,
  },
  {
    name: 'water weird',
    area: 'nature',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'will-o-wisp',
    area: 'nature',
    type: 'undead',
    hp: 1,
  },
  {
    name: 'wyvern',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'yeti',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'abominable yeti',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'yuan-ti abomination',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'yuan-ti malison',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'yuan-ti pureblood',
    area: 'nature',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'bandit',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'bandit captain',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'scout',
    area: 'nature',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'magmin',
    area: 'other plane',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'fire snake',
    area: 'other plane',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'salamander',
    area: 'other plane',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'red slaad',
    area: 'other plane',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'slaad tadpole',
    area: 'other plane',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'blue slaad',
    area: 'other plane',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'green slaad',
    area: 'other plane',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'grey slaad',
    area: 'other plane',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'death slaad',
    area: 'other plane',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'succubus',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'xorn',
    area: 'other plane',
    type: 'elemental',
    hp: 1,
  },
  {
    name: 'arcanaloth',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'mezzoloth',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'nycaloth',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'ultroloth',
    area: 'other plane',
    type: 'fiend',
    hp: 1,
  },
  {
    name: 'ankheg',
    area: 'underground',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'basilisk',
    area: 'underground',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'behir',
    area: 'underground',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'carrion crawler',
    area: 'underground',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'cloaker',
    area: 'underground',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'darkmantle',
    area: 'underground',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'drider',
    area: 'underground',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'duergar',
    area: 'underground',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'drow',
    area: 'underground',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'drow elite warrior',
    area: 'underground',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'drow mage',
    area: 'underground',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'drow priestess',
    area: 'underground',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'ettercap',
    area: 'underground',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'flumph',
    area: 'underground',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'fomorian',
    area: 'underground',
    type: 'giant',
    hp: 1,
  },
  {
    name: 'gas spore',
    area: 'underground',
    type: 'plant',
    hp: 1,
  },
  {
    name: 'shrieker',
    area: 'underground',
    type: 'plant',
    hp: 1,
  },
  {
    name: 'violet fungus',
    area: 'underground',
    type: 'plant',
    hp: 1,
  },
  {
    name: 'deep gnome',
    area: 'underground',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'grick',
    area: 'underground',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'grick alpha',
    area: 'underground',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'grimlock',
    area: 'underground',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'hook horror',
    area: 'underground',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'kuo-toa',
    area: 'underground',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'kuo-toa archpriest',
    area: 'underground',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'kuo-toa whip',
    area: 'underground',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'myconid sprout',
    area: 'underground',
    type: 'plant',
    hp: 1,
  },
  {
    name: 'spore servant',
    area: 'underground',
    type: 'plant',
    hp: 1,
  },
  {
    name: 'myconid adult',
    area: 'underground',
    type: 'plant',
    hp: 1,
  },
  {
    name: 'myconid sovereign',
    area: 'underground',
    type: 'plant',
    hp: 1,
  },
  {
    name: 'nothic',
    area: 'underground',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'otyugh',
    area: 'underground',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'piercer',
    area: 'underground',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'quaggoth',
    area: 'underground',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'roper',
    area: 'underground',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'rust name',
    area: 'underground',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'troglodyte',
    area: 'underground',
    type: 'humanoid',
    hp: 1,
  },
  {
    name: 'umber hulk',
    area: 'underground',
    type: 'monstrosity',
    hp: 1,
  },
  {
    name: 'aboleth',
    area: 'water',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'chuul',
    area: 'water',
    type: 'aberration',
    hp: 1,
  },
  {
    name: 'sea hag',
    area: 'water',
    type: 'fey',
    hp: 1,
  },
].map((m) => Object.freeze(m));

// TODO update as new monster sprites are added
const index = monsterData.findIndex((m) => m.name === 'roc');
export const monsters = monsterData.slice(0, index + 1);
